name: PHP Composer

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_ENVIRONMENT: ${{ secrets.VITE_SERVER_URL }}
      app.baseURL: ${{ secrets.VITE_NODE_ENV }}

    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '8.2' # Adjust PHP version as needed

          - name: Install dependencies
            run: composer install --no-interaction --prefer-dist

          - name: Run tests (optional)
            run: vendor/bin/phpunit # Or your preferred testing command

          - name: Deploy to server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              script: |
                cd /var/www/html/cafeboss_helios # Adjust to your server path
                git pull origin main
                rm -rf .env
                cp /var/www/html/.env /var/www/html/cafeboss_helios/.env
                composer install --no-interaction --prefer-dist